const tools=[
['profit','💰','Kalkulator Untung','Hitung keuntungan dan persentase dari modal dan harga jual.',['Modal','Harga jual'],v=>{const p=v[1]-v[0];return `Keuntungan: <b>Rp ${idr(p)}</b><br>Persentase dari modal: <b>${pct(p,v[0])}%</b>`}],
['price','🛒','Kalkulator Harga Jual','Tentukan harga jual berdasarkan target margin.',['Modal','Target margin (%)'],v=>v[1]>=100?'Margin harus di bawah 100%.':`Harga jual: <b>Rp ${idr(v[0]/(1-v[1]/100))}</b>`],
['margin','📊','Kalkulator Margin','Hitung margin keuntungan dari harga jual.',['Harga jual','Modal/HPP'],v=>v[0]===0?'Harga jual harus lebih dari 0.':`Margin: <b>${pct(v[0]-v[1],v[0])}%</b>`],
['discount','🏷️','Kalkulator Diskon','Hitung harga setelah diskon dan jumlah potongan.',['Harga awal','Diskon (%)'],v=>`Harga akhir: <b>Rp ${idr(v[0]*(1-v[1]/100))}</b><br>Potongan: Rp ${idr(v[0]*v[1]/100)}`],
['bep','⚖️','Kalkulator BEP','Hitung titik impas dalam jumlah unit.',['Biaya tetap','Harga/unit','Biaya variabel/unit'],v=>{const d=v[1]-v[2];return d<=0?'Harga/unit harus lebih tinggi dari biaya variabel/unit.':`BEP: <b>${(v[0]/d).toFixed(2)} unit</b>`}],
['roi','📈','Kalkulator ROI','Hitung return on investment.',['Investasi','Keuntungan'],v=>v[0]===0?'Investasi harus lebih dari 0.':`ROI: <b>${pct(v[1],v[0])}%</b>`],
['percent','％','Kalkulator Persentase','Hitung nilai A sebagai persentase dari B.',['Nilai A','Nilai B'],v=>v[1]===0?'Nilai B harus lebih dari 0.':`Hasil: <b>${pct(v[0],v[1])}%</b>`],
['markup','➕','Kalkulator Markup','Hitung harga jual berdasarkan markup dari modal.',['Modal','Markup (%)'],v=>`Harga jual: <b>Rp ${idr(v[0]*(1+v[1]/100))}</b>`],
['target','🎯','Target Harga + Laba','Cari harga jual untuk mendapatkan laba rupiah tertentu.',['Modal','Target laba'],v=>`Harga jual: <b>Rp ${idr(v[0]+v[1])}</b>`],
['commission','🤝','Kalkulator Komisi','Hitung komisi berdasarkan nilai transaksi.',['Nilai transaksi','Komisi (%)'],v=>`Komisi: <b>Rp ${idr(v[0]*v[1]/100)}</b><br>Sisa setelah komisi: Rp ${idr(v[0]*(1-v[1]/100))}`],
['revenue','🧾','Target Omzet','Hitung jumlah penjualan yang dibutuhkan untuk mencapai omzet.',['Target omzet','Harga jual/unit'],v=>v[1]===0?'Harga jual/unit harus lebih dari 0.':`Minimal penjualan: <b>${Math.ceil(v[0]/v[1])} unit</b>`],
['growth','🚀','Kalkulator Pertumbuhan','Hitung persentase pertumbuhan dari angka lama ke angka baru.',['Nilai lama','Nilai baru'],v=>v[0]===0?'Nilai lama harus lebih dari 0.':`Pertumbuhan: <b>${pct(v[1]-v[0],v[0])}%</b>`]
];
const grid=document.querySelector('#grid'),count=document.querySelector('#count'),search=document.querySelector('#search'),modal=document.querySelector('#modal'),body=document.querySelector('#body'),toast=document.querySelector('#toast');
function idr(n){return Math.round(Number(n)||0).toLocaleString('id-ID')}
function pct(a,b){return ((a/b)*100).toFixed(2)}
function render(q=''){const a=tools.filter(t=>(t[2]+' '+t[3]).toLowerCase().includes(q.toLowerCase().trim()));count.textContent=a.length+' tools';grid.innerHTML=a.map(t=>`<article class="card" onclick="calc('${t[0]}')">${t[1]}<h3>${t[2]}</h3><p>${t[3]}</p><b>Gunakan gratis →</b></article>`).join('')||'<div class="empty">Tool tidak ditemukan. Coba kata kunci lain.</div>'}
function calc(id){const t=tools.find(x=>x[0]===id);body.innerHTML=`<h2>${t[1]} ${t[2]}</h2><p>${t[3]}</p>${t[4].map((x,i)=>`<div class="field"><label>${x}</label><input id="f${i}" type="number" min="0" inputmode="decimal" placeholder="Masukkan angka"></div>`).join('')}<button class="primary" onclick="runCalc('${id}')">Hitung</button><div class="result" id="res">Hasil akan muncul di sini.</div>`;openM()}
function runCalc(id){const t=tools.find(x=>x[0]===id),v=t[4].map((_,i)=>Number(document.querySelector('#f'+i).value||0));document.querySelector('#res').innerHTML=t[5](v)}
function contentTool(type){const names={caption:'Pembuat Caption Produk',description:'Pembuat Deskripsi Produk',hashtag:'Ide Hashtag',hook:'Ide Hook Video'};body.innerHTML=`<h2>${names[type]}</h2><div class="field"><label>Nama produk</label><input id="p" placeholder="Contoh: Jaket pria"></div><div class="field"><label>Keunggulan / tema</label><textarea id="k" rows="3" placeholder="Contoh: ringan, nyaman, harga terjangkau"></textarea></div><button class="primary" onclick="makeContent('${type}')">Buat draft</button><div class="result" id="res">Hasil akan muncul di sini.</div>`;openM()}
function makeContent(type){const p=document.querySelector('#p').value.trim()||'produk ini',k=document.querySelector('#k').value.trim()||'nyaman dan praktis';let r='';if(type==='caption')r=`✨ <b>${escapeHTML(p)}</b> siap menemani aktivitasmu!<br><br>${escapeHTML(k)}. Cocok untuk kamu yang mencari produk praktis dan nyaman.<br><br>📩 Hubungi kami untuk pemesanan.`;if(type==='description')r=`<b>${escapeHTML(p)}</b><br><br>Produk dengan keunggulan ${escapeHTML(k)}. Cocok untuk kebutuhan sehari-hari. Hubungi penjual untuk detail ukuran, warna, stok, dan pengiriman.`;if(type==='hashtag'){const tag=p.toLowerCase().replace(/[^a-z0-9\s]/gi,'').trim().replace(/\s+/g,'');r=`#${tag} #umkm #jualanonline #produkindonesia #belanjaonline #produklokal #bisnisonline #tokoonline`;}if(type==='hook')r=`1. “Kalau kamu sedang cari ${escapeHTML(p)}, jangan scroll dulu.”<br><br>2. “3 alasan kenapa ${escapeHTML(p)} layak kamu pertimbangkan.”<br><br>3. “Aku baru menemukan ${escapeHTML(p)} dengan keunggulan ${escapeHTML(k)}.”<br><br>4. “Sebelum beli ${escapeHTML(p)}, cek ini dulu.”`;document.querySelector('#res').innerHTML=r+`<br><button class="copybtn" onclick="copyText(document.querySelector('#res').innerText)">Salin hasil</button>`}
function escapeHTML(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openM(){modal.classList.remove('hidden')}function closeM(){modal.classList.add('hidden')}modal.onclick=e=>{if(e.target===modal)closeM()};search.oninput=e=>render(e.target.value);
async function copyText(text){try{await navigator.clipboard.writeText(text);showToast('Berhasil disalin ✓')}catch(e){showToast('Tidak bisa menyalin otomatis di browser ini')}}
async function shareSite(){if(navigator.share){try{await navigator.share({title:'ToolsKu',text:'Tools bisnis gratis tanpa daftar',url:location.href})}catch(e){}}else copyText(location.href)}
function showToast(msg){toast.textContent=msg;toast.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.add('hidden'),1800)}
render();
